# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "uv"
    directories: # Location of package manifests
      - "/"
    schedule:
      interval: "weekly"
    commit-message:
      # Use a conventional commit tag
      prefix: "chore(deps)"
    groups:
      patch:
        update-types: ["patch"]
      minor:
        update-types: ["minor"]
      # Major updates still generate individual PRs

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      # Use a conventional commit tag
      prefix: "ci(deps)"
