[default]
locale = "en-us"
extend-ignore-words-re = [
    "^[a-zA-Z]?[a-zA-Z]?[a-zA-Z]?$",  # Ignore words up to 3 characters
    "\\$[^\\$]*\\$",  # Ignore content between single $...$
    "\\$\\$[^\\$]*\\$\\$",  # Ignore content between double $$...$$
]

[default.extend-words]
arange = "arange"  # e.g. `numpy.arange`
Aer = "Aer"  # e.g. `qiskit.providers.aer`
aer = "aer"  # e.g. `qiskit.providers.aer`
anc = "anc"  # e.g. ancilla
braket = "braket"  # MathJax extension for bra-ket notation
NDArray = "NDArray"  # e.g. `numpy.typing.NDArray`
Strang = "Strang"  # e.g. Strang splitting
Incrementers = "Incrementers"  # e.g. incrementer circuits (typos false positive)
