blank_issues_enabled: true
contact_links:
  - name: Questions & Discussion
    url: https://github.com/Quantinuum/guppy-algorithms/discussions
    about: Ask questions or start a discussion about guppy-algorithms.
